---
- name: Install Docker
  become: yes
  yum:
    name: docker
    state: present
  notify: Start Docker

- name: Enable Docker at boot
  become: yes
  systemd:
    name: docker
    enabled: yes

- name: Start Docker service
  become: yes
  service:
    name: docker
    state: started
